### ISSUE TITLE
Error when loading .bcs object into BBrowser

### ISSUE THREAD

**Issue by chris-rands** [bioturing/pyBCS#15]
Error: Submit study "study name" failed- something went wrong while parsing
```
Error in zip::unzip(arg$input_path[[1]], exdir = tmp.dir) : zip error: `Cannot open zip file `file.bcs` for reading` in file `zip.c:140`
```
When I load the .h5ad scanpy object directly, it works, thanks

**Comment by chris-rands** [comment]
Also the .h5ad object is 581M but the .bcs object is 2.8G - is that normal?

**Comment by JATC1024** [comment]
Could you provide some information, such as:
- Did you use local mode or server mode when you submit the bcs file?
- What is the exact path of the bcs file on your computer?
- What is the version of BBrowser you are using?
If it's convenience for you, please provide us the h5ad file or its structure. It will be easier for us to detect the bug if we can take a look at the file. 

Btw, the bcs file in some cases can be 3 or 4 times larger than the h5ad file. We will try to take care of this in future developments

**Comment by JATC1024** [comment]
Just a side note, BBrowser will update automatically when ever an update is available. So the next time you open it, please check for the version before it gets updated.

**Comment by chris-rands** [comment]
Sure
- Local
- `~/Downloads/object.bcs`
- Version 2.7.44

The Anndata object looks like this:
```
AnnData object with n_obs × n_vars = 31948 × 28100
    obs: 'doublet_scores', 'predicted_doublets', 'batch', 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'umap_density_batch', 'leiden', 'leiden_high'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: "dendrogram_['batch']", "dendrogram_['leiden']", 'diffmap_evals', 'draw_graph', 'enrichments', 'hvg', 'leiden', 'leiden_sizes', 'neighbors', 'paga', 'pca', 'rank_genes_groups', 'umap', 'umap_density_batch_params'
    obsm: 'X_diffmap', 'X_draw_graph_fa', 'X_pca', 'X_tsne', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
```

**Comment by JATC1024** [comment]
What OS are you using? Can you try a few things:
- Make a copy of the file and change its name to object.zip and then unzip it and see if any errors occur. Doing this will tell us if the file is corrupted.
- Move the file to a new location which is easier for a program to read, such as D:/object.bcs and then submit it again. My guess is that at some point our program cannot parse the path to the file.

**Comment by chris-rands** [comment]
macOS - I am able to unzip it and extract the X/main/* files and directories

**Comment by JATC1024** [comment]
We just release a new version which could potentially fix your problem. Please try again and let us know if the problem still persists.

Beside, I notice that the error message says that it cannot open "file.bcs" while your file name is "object.bcs". Is this actually the file that you submitted?

**Comment by chris-rands** [comment]
Seems fixed with the latest release, thanks
