### ISSUE TITLE
pyBCS cannot find bcs [bug]

### ISSUE THREAD

**Issue by bkellmono** [bioturing/pyBCS#25]
pyBCS (which seems only to load at pybcs) fails to load and cannot find BCS within bcs.py

![image](https://user-images.githubusercontent.com/81656080/113064349-ab83c580-916b-11eb-9746-70c42a1922fb.png)

I'm using python 3.7.3

**Comment by JATC1024** [comment]
It should be "pip install pyBCS-bioturing". It seems that "pybcs" is different package. We should write a few lines to README to clarify this.

**Comment by bkellmono** [comment]
Ah thanks! Worked perfectly
