### ISSUE TITLE
Error importing .bcs converted from scanpy h5ad

### ISSUE THREAD

**Issue by lindafong** [bioturing/pyBCS#32]
[2021-12-03 22:02:24][ProcessFromObject] Extracting data...
[2021-12-03 22:14:56][ProcessFromObject] BCS version: 0.4.3
[2021-12-03 22:14:56][ProcessFromObject] Expanding data...

Error in NoraCommon::LightTranspose(file.path(bcs.dir, "main", "matrix.hdf5")) : 
An error happened, Please post an issue at: https://github.com/bioturing/pyBCS/issues

ERROR

I am trying to transfer a scanpy h5ad to bcs to be loaded into the BioTuring software. It seems as though pyBCS runs correctly, see below, but when I go into the software and upload the data, it returns an error.

When running pyBCS, it doesn't seem like there is a problem, here is the output:
Writing main/metadata/metalist.json
Cannot convert alignment_sample_origin to numeric, treating as categorical
Cannot convert sample_id to numeric, treating as categorical
Cannot convert Sample to numeric, treating as categorical
Cannot convert Genotype to numeric, treating as categorical
Cannot convert Timepoint to numeric, treating as categorical
Cannot convert Treatment to numeric, treating as categorical
Cannot convert Sequencing to numeric, treating as categorical
Cannot convert 10x to numeric, treating as categorical
Cannot convert File_name to numeric, treating as categorical
Cannot convert Quality to numeric, treating as categorical
Cannot convert leiden_immune_1 to numeric, treating as categorical
"cell_containing_barcode" is not numeric or categorical, ignoring
"Immune" is not numeric or categorical, ignoring
Found graph based clustering in metadata with keyword leiden_immune_1
Writing main/metadata/ed2e4ce2697541d49bbc5908f6629f28.json
Writing main/metadata/a8f1dda538ba40e9a30f20d9d0aa7b7b.json
Writing main/metadata/fa76fb5b1d26486bb6a229f3689a42cb.json
Writing main/metadata/566ee7bc36004f7cb481ce71dbeec01f.json
Writing main/metadata/d597e8c63185453cbb97982a4219da01.json
Writing main/metadata/c0ffa68c0b9341d6bdaae9b42a44826a.json
Writing main/metadata/3573d1015b194617b26cd2a38a688a1a.json
Writing main/metadata/b42f8e0ae2a246d38523c3b2f9d30c5e.json
Writing main/metadata/dcf64fb0f8654bf6b038a7912e22598f.json
Writing main/metadata/a8ffdaf5ec7f4eae9dc251f17588e496.json
Writing main/metadata/af77706b24d5462bb672fd532a41d60f.json
Writing main/metadata/f44b74199d5a406ca626b556fc92f5a7.json
Writing main/metadata/993fa6d370374d7ba318d2f50bb1a6e4.json
Writing main/metadata/953c2477ea9b4108a7024715885fc73a.json
Writing main/metadata/ac80143ad69940cf87899469534c82df.json
Writing main/metadata/f1ba6fb39bf1492b8a316b55df32023c.json
Writing main/metadata/ed2b9379b1eb4ff29eb8ffaf3bfee243.json
Writing main/metadata/81b47c0eb5624117bcfd182479b6ed89.json
Writing main/metadata/1fee9947d12346ceb9f30e55425e0c10.json
Writing main/metadata/3a1546ddfce344b9be0a553385ff3fec.json
Writing main/metadata/4cce4b4d49b84c7e9c67fbb921f03afa.json
Writing main/metadata/b5110ac1994c4a8490e230ed6cf2358f.json
Writing main/metadata/b7e2c8c6b2f84052b783b7ff06da0caa.json
Writing main/metadata/52a61846c7314d5399f93457a8cde83c.json
Writing main/metadata/c99b773a39a744058585a6d32cb2f1b0.json
Writing main/metadata/2ac7369454084e8d9b43619b3ffbd8ac.json
Writing main/metadata/graph_based.json
Writing dimred
Writing X_pca
X_pca has more than 3 dimensions, using only the first 3 of them
Writing X_pca_harmony
X_pca_harmony has more than 3 dimensions, using only the first 3 of them
Writing X_umap
Writing main/dimred/meta
Writing main/matrix.hdf5
Normalized data and raw data are both available
Writing group "countsT"
Raw data and normalized data do not share the same indptr and indices
Writing group "normalizedT"
Writing group "colsum"
Writing to zip
Writing main/barcodes.tsv
Writing main/genes.tsv
Writing main/gene_gallery.json
Writing run_info.json

**Comment by JATC1024** [comment]
Hi, thanks for reporting.

Can you share the log files at C:\Users\%USERNAME%\.BioTBData\Data\Logs? You can pick just the ones from the date that you got the error.

Also, may I ask what is the size of the matrices? Are they sparse or dense? Did you submit the bcs file in server mode or local mode? From the log of pyBCS I can see that the raw and normalized data do not share the same "indptr" and "indices". It means that the positions of the non-zero values in those matrices are not the same, which is strange. Usually, if you follow scanpy's normalization pipeline then those positions will be the same. So I suspect that somewhere in the normalization process, the normalized matrix became dense and lead to memory allocation error in bbrowser.

**Comment by TriLe965** [comment]
I'll close this thread because it is active. Feel please to re-open it.
